export const CANVAS_WIDTH_DPX = 176;
export const CANVAS_WIDTH_CPX = CANVAS_WIDTH_DPX * 2;
export const CHAR_WIDTH_CPX = 6;
export const LINE_HEIGHT_CPX = 10;

export const LINE_GAP_CPX = 4;
export const N_CHARS_PER_LINE = CANVAS_WIDTH_CPX / CHAR_WIDTH_CPX; // 30
export const N_CHARS_OF_INDENT = 2;
export const N_CHARS_OF_SPACE = 1;

export const INDENT_BLOCK_WIDTH_CPX = CHAR_WIDTH_CPX;
export const INDENT_BLOCK_SPACE_WIDTH_CPX = CHAR_WIDTH_CPX;
export const INDENT_BLOCK_TOTAL_WIDTH_CPX =
    INDENT_BLOCK_WIDTH_CPX + INDENT_BLOCK_SPACE_WIDTH_CPX;
export const VISIBILITY_MARGIN_CPX = 3100;
